name: CI FOR Deploy PROD

on:
  push:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, 'feature/') }} 
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 17
      uses: actions/setup-node@v2
      with:
        node-version: '17.4.0'

    - name: 🔨 Install Project dependencies
      run: |
        node -v
        npm -v
        npm install -g @angular/cli
        npm install --force

    - name: 🔨 Build Project
      run: |
        ng lint
        npm run test
        npm run build

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/landing ${{ secrets.AWS_BUCKET_NAME }}